# Generated by Django 5.0 on 2023-12-25 05:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=tinymce.models.HTMLField(),
        ),
    ]
