# Generated by Django 5.0 on 2023-12-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_company_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("Softwere devloper", "Softwere devloper"),
                    ("Web Devloper", "Full Stack Devloper"),
                    ("Embedded Engineer", "Sr Embedded Engineer"),
                ],
                max_length=50,
            ),
        ),
    ]
